export const FETCH_BITCOIN_VALUE_START = 'FETCH_BITCOIN_VALUE_START'
export const FETCH_BITCOIN_VALUE_SUCCESS = 'FETCH_BITCOIN_VALUE_SUCCESS'
export const FETCH_BITCOIN_VALUE_FAILED = 'FETCH_BITCOIN_VALUE_FAILED'

export const FETCH_BITCOIN_CHART_START = 'FETCH_BITCOIN_CHART_START'
export const FETCH_BITCOIN_CHART_SUCCESS = 'FETCH_BITCOIN_CHART_SUCCESS'
export const FETCH_BITCOIN_CHART_FAILED = 'FETCH_BITCOIN_CHART_FAILED'

